version: '3.3'

volumes:
  static:
  media:

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - ../frontend/:/app/result_build/
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static:/backend_static
      - media:/app/media
  nginx:
    image: nginx:1.19.3
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/var/www/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
