# Generated by Django 3.2 on 2023-09-19 22:35

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[recipes.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
