# Generated by Django 3.2 on 2023-09-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230914_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countingredient',
            old_name='amount',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='countingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
