# Generated by Django 3.2 on 2023-09-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countingredient', to='recipes.recipe', unique=True, verbose_name='Рецепт'),
        ),
    ]
