# Generated by Django 3.2 on 2023-09-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countingredient',
            old_name='count',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='countingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
