# Generated by Django 3.2 on 2023-09-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230921_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сomposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Мера')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='recipes.ingredient', verbose_name='Продукты')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Мера продуктов',
                'verbose_name_plural': 'Мера продуктов',
                'ordering': ('recipe',),
                'default_related_name': 'composition',
            },
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Сomposition', to='recipes.Ingredient', verbose_name='Продукты'),
        ),
        migrations.AddConstraint(
            model_name='сomposition',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='unique count ingredient'),
        ),
    ]
