# Generated by Django 3.2 on 2023-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230920_1019'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='countingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='unique coun tingredient'),
        ),
    ]
