# Generated by Django 3.2 on 2023-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230914_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.CountIngredient', verbose_name='Ингредиенты'),
        ),
    ]
