name: Foofgram workflow
on:
  push:
    branches:
      - dev

jobs:
  tests_backend:
    name: Тест бэкэнда
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 

    steps:
    - name: Копируем код проекта
      uses: actions/checkout@v3
    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Обновляем pip, устанавливаем зависимости
      run: |
        python -m pip install --upgrade pip 
        pip install -r backend/requirements.txt
    - name: Тесты flake8 
      run: python -m flake8 .