name: Foodgram workflow
on:
  push:
    branches:
      - '*'

jobs:
  build_and_push_to_docker_hub:
    name: Билд и пуш на Docker Hub бэкэнда
    runs-on: ubuntu-latest
    steps:
      - name: Получение исходного кода из репозитория
        uses: actions/checkout@v3
      - name: Установка сборщика контейнеров Docker
        uses: docker/setup-buildx-action@v2
      - name: Авторизация на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Билд и пуш образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
  
  build_frontend_and_push_to_docker_hub:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Билд и пуш на Docker Hub фронтенда
    runs-on: ubuntu-latest
    steps:
      - name: Получение исходного кода из репозитория
        uses: actions/checkout@v3
      - name: Установка сборщика контейнеров Docker
        uses: docker/setup-buildx-action@v2
      - name: Авторизация на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Билд и пуш образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest 
  
